<a href="https://pcpartpicker.com/list/Cs6brM">PCPartPicker Part List</a>
<table class="pcpp-part-list">
	<thead>
		<tr>
			<th>Type</th>
			<th>Item</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="pcpp-part-list-type">CPU</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/rkwkcf/amd-threadripper-3970x-37-ghz-32-core-processor-100-100000011wof"
					>AMD Threadripper 3970X 3.7 GHz 32-Core Processor</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/rkwkcf/amd-threadripper-3970x-37-ghz-32-core-processor-100-100000011wof"
					>$1650.00 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">CPU Cooler</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/sccgXL/corsair-icue-h150i-elite-capellix-xt-6557-cfm-liquid-cpu-cooler-cw-9060073-ww"
					>Corsair iCUE H150i ELITE CAPELLIX XT 65.57 CFM Liquid CPU Cooler</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/sccgXL/corsair-icue-h150i-elite-capellix-xt-6557-cfm-liquid-cpu-cooler-cw-9060073-ww"
					>$166.51 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">Motherboard</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/zcyqqs/asus-rog-zenith-ii-extreme-alpha-eatx-strx4-motherboard-rog-zenith-ii-extreme-alpha"
					>Asus ROG ZENITH II EXTREME ALPHA EATX sTRX4 Motherboard</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/zcyqqs/asus-rog-zenith-ii-extreme-alpha-eatx-strx4-motherboard-rog-zenith-ii-extreme-alpha"
					>$1599.00 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">Memory</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/k2mFf7/corsair-vengeance-lpx-64-gb-2-x-32-gb-ddr4-3200-memory-cmk64gx4m2e3200c16"
					>Corsair Vengeance LPX 64 GB (2 x 32 GB) DDR4-3200 CL16 Memory</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/k2mFf7/corsair-vengeance-lpx-64-gb-2-x-32-gb-ddr4-3200-memory-cmk64gx4m2e3200c16"
					>$89.99 @ Newegg</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">Storage</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/f3cRsY/samsung-980-pro-2-tb-m2-2280-nvme-solid-state-drive-mz-v8p2t0bam"
					>Samsung 980 Pro 2 TB M.2-2280 PCIe 4.0 X4 NVME Solid State Drive</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/f3cRsY/samsung-980-pro-2-tb-m2-2280-nvme-solid-state-drive-mz-v8p2t0bam"
					>$189.99 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">Video Card</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/K688TW/nvidia-founders-edition-geforce-rtx-4070-12-gb-video-card-900-1g141-2544-000"
					>NVIDIA Founders Edition GeForce RTX 4070 12 GB Video Card</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/K688TW/nvidia-founders-edition-geforce-rtx-4070-12-gb-video-card-900-1g141-2544-000"
					>$1399.00 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">Case</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/dyLwrH/fractal-design-define-7-xl-atx-full-tower-case-fd-c-def7x-01"
					>Fractal Design Define 7 XL ATX Full Tower Case</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/dyLwrH/fractal-design-define-7-xl-atx-full-tower-case-fd-c-def7x-01"
					>$224.99 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td class="pcpp-part-list-type">Power Supply</td>
			<td class="pcpp-part-list-item"
				><a
					href="https://pcpartpicker.com/product/XZsV3C/corsair-rm1000x-2024-1000-w-fully-modular-atx-power-supply-cp-9020271-na"
					>Corsair RM1000x (2024) 1000 W Fully Modular ATX Power Supply</a
				></td
			>
			<td class="pcpp-part-list-price">
				<a
					href="https://pcpartpicker.com/product/XZsV3C/corsair-rm1000x-2024-1000-w-fully-modular-atx-power-supply-cp-9020271-na"
					>$169.99 @ Amazon</a
				>
			</td>
		</tr>
		<tr>
			<td></td>
			<td class="pcpp-part-list-price-note"
				>Prices include shipping, taxes, rebates, and discounts</td
			>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td class="pcpp-part-list-total">Total</td>
			<td class="pcpp-part-list-total-price">$5489.47</td>
		</tr>
		<tr>
			<td></td>
			<td class="pcpp-part-list-price-note"
				>Generated by <a href="https://pcpartpicker.com">PCPartPicker</a> 2025-04-19 22:18 EDT-0400</td
			>
			<td></td>
		</tr>
	</tbody>
</table>
